dist:
  name: otelcol-simple
  description: Basic OTel Collector distribution for Metrics exporter
  output_path: ./otelcol-simple
  otelcol_version: 0.108.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.108.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.108.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.108.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.108.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.108.0
