receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: 0.0.0.0:9100

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]
  telemetry:
    logs:
      level: debug
